version: "3"
services:
    webapp:
      build: ./webapp/.
      depends_on:
        - database
      ports:
        - "8080:80"
      restart: 'always'
      
    database:
      build: ./database/.
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mydb
        # MYSQL_USER: newuser
        # MYSQL_PASSWORD: newuserpass
        MYSQL_PORT: 3306
      restart: 'always'
      hostname: database